/*
	This code was generated by a tool.
    Changes to this file will be lost if the code is regenerated.
*/


 
 
 

	export const enum QuestionType {
		Unknown = 0,
		SingleRight = 1
	}
	export const enum QuizFlowCommandType {
		Unknown = 0,
		QuizProceed = 1,
		QuizFinish = 2
	}



	export class Answer {
		id: number;
		isCorrect: boolean;
		templateId: number;
	}
	export class AnswerTemplate {
		id: number;
		isCorrect: boolean;
		order: number;
		text: string;
	}
	export class ClientExceptionContract {
		clientPlatform: string;
		correlationId: string;
		errorCode: string;
		message: string;
		stackTrace: string;
	}
	export class ExceptionContract {
		correlationId: string;
		errorCode: string;
		extension: any;
		message: string;
	}
	export interface IException {
		errorCode: string;
		extension: any;
		message: string;
	}
	export class Question {
		answers: Answer[];
		dateEnd: Date;
		dateStart: Date;
		id: number;
		isAnswered: boolean;
		order: number;
		quiz: Quiz;
		templateId: number;
	}
	export class QuestionTemplate {
		answers: AnswerTemplate[];
		id: number;
		questionType: QuestionType;
		text: string;
	}
	export class Quiz {
		currentQuestion: Question;
		dateEnd: Date;
		dateStart: Date;
		id: number;
		isCompleted: boolean;
		questions: Question[];
		templateId: number;
	}
	export class QuizFlowCommandContract {
		commandType: QuizFlowCommandType;
	}
	export class QuizFlowCommandFinishContract extends QuizFlowCommandContract {
		commandType: QuizFlowCommandType;
	}
	export class QuizFlowCommandProceedContract extends QuizFlowCommandContract {
		commandType: QuizFlowCommandType;
		questionId: number;
		quizId: number;
		template: QuestionTemplate;
	}
	export class QuizQuestionTemplate {
		enabled: boolean;
		order: number;
		questionTemplate: QuestionTemplate;
		questionTemplateId: number;
		quizTemplate: QuizTemplate;
		quizTemplateId: number;
	}
	export class QuizTemplate {
		description: string;
		id: number;
		title: string;
	}
	export class QuizTemplateDetailsContract {
		questionsCount: number;
		quizTemplate: QuizTemplate;
	}
	export class Score {
		id: number;
		quizId: number;
		scoresAmount: number;
	}


