version: '3'

services:
  database:
    image: postgres
    restart: always
    environment: &environment
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    volumes:
      - data-volume:/var/lib/postgresql/data
  quizservice:
    image: quizservice
    build:
      context: ./QuizService
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment: *environment
    depends_on:
    - database
  quizclient:
    image: quizclient
    build:
      context: ./QuizClient
      dockerfile: Dockerfile
    ports:
      - "80:80"      
    depends_on:
    - quizservice    

volumes:
  data-volume: