version: '3'

services:
  database:
    image: postgres:10.4
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - data-volume:/var/lib/postgresql/data
  quizservice:
    image: bocharovf/quizservice
    restart: always
    environment:
      - APPINSIGHTS_INSTRUMENTATIONKEY
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - QUIZ_ADMIN_EMAIL
      - QUIZ_ADMIN_PASSWORD
    depends_on:
    - database
  quizclient:
    image: bocharovf/quizclient
    restart: always
    ports:
      - "80:80"
    depends_on:
    - quizservice

volumes:
  data-volume: